In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df.head()

<body style="background-color:powderblue;">
<h1 style="text-align:center;"> Exploratory Data Analysis </h1>

<p> This data set contains properties of different car models. It contains 12 columns. </p>
<p> We employ data science methodology to wrangle and explore this data set so as to obtain useful insight from it. </p>
<p> The objectives include comparing different car models on how well they perform, the weight of each model, the cylinder size which is a primary determinant of power, speed and fuel consuption. </p>

<p> Below are some of the exploratory data analysis that will be performed on the data set: </p>

<ul>
    <li> Import the required data set </li>
    <li> Get the basic information on the data types </li>
    <li> Have a quick view of the data set already imported into a dataframe </li>
    <li> Get the statistical summary of the dataframe </li>
</ul>
    
</body>

In [6]:
df = pd.read_csv("mtcars.csv")
df.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [10]:
len(df.columns)

12

<p> The dataset has 12 columns. From the preview, it is shown that the first column is a categorical variable and the remaining columns can be also placed within

In [25]:
desired_list =  ["model", "cyl", "vs", "am", "gear", "carb"]

for i in desired_list:
    print(df[i].unique())
    print("")

['Mazda RX4' 'Mazda RX4 Wag' 'Datsun 710' 'Hornet 4 Drive'
 'Hornet Sportabout' 'Valiant' 'Duster 360' 'Merc 240D' 'Merc 230'
 'Merc 280' 'Merc 280C' 'Merc 450SE' 'Merc 450SL' 'Merc 450SLC'
 'Cadillac Fleetwood' 'Lincoln Continental' 'Chrysler Imperial' 'Fiat 128'
 'Honda Civic' 'Toyota Corolla' 'Toyota Corona' 'Dodge Challenger'
 'AMC Javelin' 'Camaro Z28' 'Pontiac Firebird' 'Fiat X1-9' 'Porsche 914-2'
 'Lotus Europa' 'Ford Pantera L' 'Ferrari Dino' 'Maserati Bora'
 'Volvo 142E']

[6 4 8]

[0 1]

[1 0]

[4 3 5]

[4 1 2 3 6 8]



In [19]:
df.shape

(32, 12)